source 'https://rubygems.org'
ruby '2.2.0'

gem 'middleman', '~> 3.3.10'
gem 'middleman-livereload', '~> 3.4.2'
gem 'middleman-autoprefixer', '>= 2.4.3'
gem 'middleman-minify-html', '>= 3.4.0'
gem 'middleman-syntax', '>= 2.0.0'
gem 'middleman-s3_sync', '>= 3.0.44'
gem 'middleman-search_engine_sitemap', '>= 1.3.0'

gem 'slim'
gem 'therubyracer'
gem 'oj'
gem 'redcarpet', '>= 3.2.3'
gem 'travis'
gem 'nokogiri'
gem 'rainbow'
gem "bootstrap-sass", require: false

platforms :mswin, :mingw do
  gem 'tzinfo-data'
  gem 'wdm', '~> 0.1.0'
end
